//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Phukienthucung.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KHACH_HANG
    {
        public int MaKH { get; set; }
        public string Ho_ten { get; set; }
        public string Tai_khoan { get; set; }
        public string Mat_khau { get; set; }
        public string Dia_chi { get; set; }
        public string Dien_thoai { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> Ngay_sinh { get; set; }
        public Nullable<System.DateTime> Ngay_cap_nhat { get; set; }
        public Nullable<byte> Gioi_tinh { get; set; }
        public int Tich_diem { get; set; }
        public Nullable<byte> Trang_thai { get; set; }
    }
}
