//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Phukienthucung.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SAN_PHAM
    {
        public int MaSP { get; set; }
        public string TenSP { get; set; }
        public string MoTa { get; set; }
        public decimal Gia { get; set; }
        public string Hinh_anh { get; set; }
        public Nullable<byte> Trang_thai { get; set; }
    }
}
